Weights:
  DA3: './weights/model.safetensors'
  DA3_CONFIG: './weights/config.json'
  SALAD: './weights/dino_salad.ckpt'

Model:
  # Resolución interna usada por DA3 para esta prueba de diagnóstico.
  # La salida final vuelve a la resolución original de los frames.
  process_res: 504
  process_res_method: 'upper_bound_resize'

  # Usa el ray head para estimar la geometría de cámara.
  use_ray_pose: True

  # Para video usamos el frame central del chunk como referencia.
  ref_view_strategy: 'middle'
  ref_view_strategy_loop: 'middle'

  # Registra image/depth/conf/intrinsics a la resolución original.
  output_at_input_resolution: True

  # Conserva también los resultados en la resolución interna de DA3.
  save_processed_results: True

  # Guarda depth antes de aplicar el factor de escala de Sim(3).
  save_unaligned_depth: True

  # Genera metric_diagnostics.csv y alignment_diagnostics.csv.
  save_metric_diagnostics: True

  # Nombres frame_000000.npz, frame_000001.npz, etc.
  frame_index_width: 6

  # Chunks mayores para dar más contexto temporal y evitar alinear cada 2 frames.
  chunk_size: 20
  overlap: 10

  # Solo se usa cuando loop_enable está activo.
  loop_chunk_size: 20
  loop_enable: False
  useDBoW: False

  # Se conservan temporales durante el diagnóstico.
  delete_temp_files: False

  # Opciones: triton, torch, numba o numpy.
  align_lib: 'torch'

  # Opciones: sim3, se3 o scale+se3.
  align_method: 'sim3'
  scale_compute_method: 'auto'
  align_type: 'dense'

  depth_threshold: 15.0

  # Guarda NPZ por frame.
  save_depth_conf_result: True

  # Guarda transformaciones de alineación dentro del NPZ.
  save_debug_info: True

  Sparse_Align:
    keypoint_select: 'orb'
    keypoint_num: 5000

  IRLS:
    delta: 0.1
    max_iters: 5
    tol: 1e-9

  Pointcloud_Save:
    sample_ratio: 0.015
    conf_threshold_coef: 0.75

Loop:
  SALAD:
    image_size: [336, 336]
    batch_size: 32
    similarity_threshold: 0.85
    top_k: 5
    use_nms: True
    nms_threshold: 25

  SIM3_Optimizer:
    lang_version: 'cpp'
    max_iterations: 30
    lambda_init: 1e-6

Realtime:
  # Puede ser un repositorio Hugging Face:
  # model_source: 'depth-anything/DA3METRIC-LARGE'
  #
  # Para Jetson recomiendo finalmente usar una carpeta local:
  model_source: 'depth-anything/DA3METRIC-LARGE'

  # DA3METRIC-LARGE:
  #depth_mode: 'metric_focal' -> con intrinsecos y extrinsecos.
  depth_mode: 'relative'
  # Resolución interna de inferencia.
  # Empezamos con 504; después probaremos 392, 336, 280, etc.
  process_res: 504
  process_res_method: 'upper_bound_resize'

  # Cámara OpenCV.
  camera_source: 0

  capture_width: 1920
  capture_height: 1080
  capture_fps: 30

  # IMPORTANTE:
  # colocar aquí los intrínsecos REALES de la cámara
  # para la resolución 1920x1080.
  fx: null
  fy: null

  # Constante definida por DA3Metric.
  metric_focal_reference: 300.0

  display: True
  display_scale: 0.5
